var = input('digite um valor: ')
print('variavel do tipo: ', type(var))
print('só tem espaços? : ', var.isspace())
print('é numero? : ', var.isnumeric())
print('é afalbetico? : ', var.isalpha())
print('é alphanumerico? : ', var.isalnum())
print('esta em maiscula? : ', var.isupper())
print('esta em minuscula? : ', var.islower())
print('esta capitalisada? : ', var.istitle())